#!/usr/bin/env bash
# post-compact-reinject.sh - re-inject schnapp-os identity + invariants after a context compaction.
#
# Fires on SessionStart with matcher "compact" (not "startup"): after the harness compacts a long
# conversation, the model can lose the core project framing CLAUDE.md set at the top. This reprints
# the load-bearing invariants as a tight primer (SessionStart stdout is auto-injected into context).
# It does NOT restate mutable state (status, counts) - those live in the trackers it points at.
# Complement to session-start-gate.sh, which runs the git/freshness gate at startup.
set -euo pipefail

cat <<'EOF'
===== schnapp-os POST-COMPACT PRIMER =====
Context was just compacted. Reload the core framing before continuing (canonical: CLAUDE.md).

This repo IS the source of the machine-wide global rule lane. Load-bearing invariants:
- Edit rules in rules/global/, never in ~/.claude/. Generated docs (CATALOG.md) are regenerated by
  scripts/gen-catalog.sh, never hand-edited (a CI freshness gate enforces this).
- State-change discipline: every state-changing commit flips its box in the live plan doc
  (docs/superpowers/plans/) AND appends a PROGRESS.md line, in the SAME commit, then pushes.
- Status lives in the trackers (PROGRESS.md + the live plan doc), never hardcoded in prose.
- Secrets are op:// references, never values.
- Main only for directed work: local review pass, then push (decisions/0016, 0017).
- Resume point = the newest, highest-numbered file in handoffs/.

If any of the above is not already in your working context, re-read CLAUDE.md and PROGRESS.md now.
===== end primer =====
EOF
