#!/usr/bin/env bash
# gen-catalog.sh - generate CATALOG.md, an inventory of the repo's
# rules, skills, commands, and hooks.
#
# The component files (skills/ commands/ agents/, rules/, hooks/) are the single source of truth. This catalog is a
# PROJECTION of them, so no doc has to hand-list "all modules" / "all skills" and go
# stale when one is added. Re-run after adding/removing a rule, skill, command, or hook.
# CI (.github/workflows/freshness.yml) regenerates and fails the push if the
# committed CATALOG.md differs - i.e. someone changed a source file but didn't regenerate.
#
# Output is deterministic (C-locale sort, no timestamps) so the CI diff is stable.
# "update-codemaps" from the plan does not apply here: this is a docs/config repo with no
# code graph to map (the only code, connectors/op-mcp/, is self-contained); the catalog IS
# the relevant generator. "update-docs" = this script today; add generators here as needed.
#
# Config: CLAUDE_KIT_REPO (default: derived from this script's location, so it runs anywhere -
# locally and in CI where the checkout is not at ~/code/schnapp-os).
set -euo pipefail
export LC_ALL=C

REPO="${CLAUDE_KIT_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OUT="${1:-$REPO/CATALOG.md}"

[ -d "$REPO/skills" ] || { echo "FATAL: component roots not found under: $REPO" >&2; exit 1; }

# --- portable frontmatter / heading helpers (BSD + GNU awk; no gawk extensions) ---
h1() { grep -m1 '^# ' "$1" 2>/dev/null | sed 's/^# *//'; }

fm() { # file key -> single-line frontmatter value (empty if absent)
  awk -v k="$2" '
    NR==1 && $0=="---" { f=1; next }
    f && $0=="---" { exit }
    f && index($0, k":")==1 { v=substr($0, length(k)+2); sub(/^[ \t]+/,"",v); print v; exit }
  ' "$1"
}

fm_paths() { # file -> comma-joined glob list under a `paths:` key (empty if none)
  awk '
    NR==1 && $0=="---" { f=1; next }
    f && $0=="---" { exit }
    f && /^paths:/ { p=1; next }
    f && p {
      if ($0 ~ /^[ \t]*-[ \t]*/) { g=$0; sub(/^[ \t]*-[ \t]*/,"",g); gsub(/"/,"",g); out=(out==""?g:out", "g) }
      else if ($0 ~ /^[^ \t]/) { p=0 }
    }
    END { print out }
  ' "$1"
}

# Ellipsis is passed as a literal UTF-8 byte string via -v (NOT an awk \x escape: mawk on the
# Linux CI runner does not interpret \xHH the way BSD awk does, which would diverge the output).
trunc() { awk -v n=160 -v ell='…' '{ if (length($0)<=n) print; else { s=substr($0,1,n); sub(/[^ ]*$/,"",s); print s ell } }'; }

# --- build the catalog into a temp file, then move into place ---
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Catalog (generated - do not edit)"
  echo
  echo "Inventory of the repo's rules, skills, commands, hooks, and agents, generated by [\`scripts/gen-catalog.sh\`](scripts/gen-catalog.sh)."
  echo "The source files are canonical; this is a projection. Re-run the generator after adding or"
  echo "removing a rule, skill, command, or hook. CI ([\`.github/workflows/freshness.yml\`](.github/workflows/freshness.yml))"
  echo "fails a push if this file is out of date. Do not hand-edit."
  echo

  # ---- Global rules ----
  echo "## Global rules (always loaded, lean)"
  echo
  for f in "$REPO"/rules/global/*.md; do
    [ -e "$f" ] || continue
    echo "- **$(h1 "$f")**: \`rules/global/$(basename "$f")\`"
  done
  echo

  # ---- Modules by dimension ----
  echo "## Rule modules (path-scoped reference library; \`@import\` per project as needed)"
  echo
  refs=""
  for dim in "$REPO"/rules/modules/*/; do
    [ -d "$dim" ] || continue
    dname="$(basename "$dim")"
    rows=""
    for f in "$dim"*.md; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      composed="$(fm "$f" composed)"
      if [ "$composed" = "false" ] || [ "${base:0:1}" = "_" ]; then
        refs="$refs- \`rules/modules/$dname/$base\`: $(h1 "$f")\n"
        continue
      fi
      mod="$(fm "$f" module)"; [ -z "$mod" ] && mod="$dname/${base%.md}"
      scope="$(fm_paths "$f")"; [ -z "$scope" ] && scope="all files (on-demand)"
      rows="$rows| \`$mod\` | $scope | $(h1 "$f") |\n"
    done
    if [ -n "$rows" ]; then
      echo "### $dname"
      echo
      echo "| Module | Scope (paths) | Title |"
      echo "|---|---|---|"
      printf "%b" "$rows"
      echo
    fi
  done
  if [ -n "$refs" ]; then
    echo "### reference-only (read on demand, not path-scoped)"
    echo
    printf "%b" "$refs"
    echo
  fi

  # ---- Skills ----
  echo "## Skills"
  echo
  for d in "$REPO"/skills/*/; do
    [ -f "$d/SKILL.md" ] || continue
    nm="$(fm "$d/SKILL.md" name)"; [ -z "$nm" ] && nm="$(basename "$d")"
    desc="$(fm "$d/SKILL.md" description | trunc)"
    echo "- **$nm**: $desc"
  done
  echo

  # ---- Commands ----
  echo "## Commands"
  echo
  for f in "$REPO"/commands/*.md; do
    [ -e "$f" ] || continue
    desc="$(fm "$f" description | trunc)"
    echo "- **/$(basename "${f%.md}")**: $desc"
  done
  echo

  # ---- Hooks (list the scripts; wiring is in .claude/settings.json + the shell) ----
  echo "## Hooks"
  echo
  echo "Scripts in \`hooks/\`, wired in the repo's \`.claude/settings.json\` (project scope)"
  echo "and by \`shell/install.sh\` at user scope (the \`global-*\` set, ADR 0033); map in"
  echo "\`hooks/README.md\`."
  echo
  for f in "$REPO"/hooks/*.sh; do
    [ -e "$f" ] || continue
    # second line of each hook script is a `# <basename> - purpose` summary;
    # drop the leading `# ` and everything through the first ` - ` separator
    # (awk index() = first occurrence, so hyphens inside basenames stay intact).
    summary="$(sed -n '2p' "$f" | sed 's/^# *//' | awk '{ i = index($0, " - "); if (i) print substr($0, i + 3); else print }')"
    echo "- **$(basename "$f")**: $summary"
  done
  echo

  # ---- Agents ----
  echo "## Agents"
  echo
  if ls "$REPO"/agents/*.md >/dev/null 2>&1; then
    for f in "$REPO"/agents/*.md; do echo "- **$(basename "${f%.md}")**"; done
  else
    echo "None yet."
  fi
  echo

  # ---- MCP connectors (static registry; LIVE health/topology is the vault credentials-state fact) ----
  echo "## MCP connectors"
  echo
  echo "Remote MCP servers in \`connectors/\`, referenced by \`.mcp.json\` (bearer \${ENV} refs) and, for"
  echo "the portal-fronted set, behind the Cloudflare portal (\`op/memory/mac/github\`; obsidian-mcp is a"
  echo "separate native-OAuth connector). This is the static inventory only; live health, auth state, and"
  echo "rotation status are the vault \`credentials-state\` fact (referenced, never restated here)."
  echo
  if ls -d "$REPO"/connectors/*/ >/dev/null 2>&1; then
    for d in "$REPO"/connectors/*/; do
      nm="$(basename "$d")"
      # one-liner = first prose line after the H1 (skips frontmatter + the H1 itself); fall back to H1
      desc="$(awk '/^# / {f=1; next} f && NF {print; exit}' "$d/README.md" | trunc)"
      [ -z "$desc" ] && desc="$(h1 "$d/README.md")"
      [ -z "$desc" ] && desc="see connectors/$nm/README.md"
      back="server.py"; [ -d "$d/src" ] && back="src/"
      echo "- **$nm**: $desc (backing: \`connectors/$nm/$back\`)"
    done
  else
    echo "None."
  fi
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "gen-catalog: wrote $OUT"
