#!/usr/bin/env bash
# gen-handoff-index.sh: generate handoffs/README.md, a thin index (number to
# H1 title, newest-first) over every session handoff (Phase 4 T4).
#
# handoffs/NNN-slug.md files are the single source of truth (append-only session
# history). This index is a PROJECTION of their H1 titles, so no doc has to
# hand-list "all handoffs" and go stale when one is added. Re-run after adding a
# handoff. CI (scripts/check-freshness.sh, .github/workflows/freshness.yml) fails
# the push if the committed index differs from a fresh regen.
#
# Handoff files are NEVER moved: 30+ docs link them as handoffs/NNN-slug.md, so
# this index sits beside them rather than reorganizing anything.
#
# Output is deterministic (C-locale sort, no timestamps) so the CI diff is stable.
#
# Config: CLAUDE_KIT_REPO (default: derived from this script's location, so it
# runs anywhere: locally and in CI where the checkout is not at ~/code/schnapp-os).
set -euo pipefail
export LC_ALL=C

REPO="${CLAUDE_KIT_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OUT="${1:-$REPO/handoffs/README.md}"

[ -d "$REPO/handoffs" ] || { echo "FATAL: handoffs/ not found under: $REPO" >&2; exit 1; }

h1() { grep -m1 '^# ' "$1" 2>/dev/null | sed 's/^# *//'; }

# --- build the index into a temp file, then move into place ---
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Handoffs - index (generated, do not edit)"
  echo
  echo "Thin index over every session handoff in this directory, generated by"
  echo "[\`scripts/gen-handoff-index.sh\`](../scripts/gen-handoff-index.sh). Handoffs are session"
  echo "history: newest-first below, and the newest is the current resume point. Files are"
  echo "append-only and stay in place (other docs link them by path) - this index never moves"
  echo "or renames a handoff. Regenerate with \`scripts/gen-handoff-index.sh\` after adding one;"
  echo "CI ([\`.github/workflows/freshness.yml\`](../.github/workflows/freshness.yml)) fails a push"
  echo "if this file is out of date."
  echo

  for f in "$REPO"/handoffs/[0-9]*.md; do
    [ -e "$f" ] || continue
    base="$(basename "$f")"
    num="${base%%-*}"
    echo "$num|- [\`$num\`]($base) $(h1 "$f")"
  done | LC_ALL=C sort -t'|' -k1,1 -r | cut -d'|' -f2- | awk 'NR==1{print $0" (resume point)"; next} {print}'
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "gen-handoff-index: wrote $OUT"
