#!/usr/bin/env bash
# gen-plugins-manifest.sh - regenerate shell/plugins-manifest.txt from THIS machine's
# live plugin state (~/.claude/plugins + user settings.json enabledPlugins). The Mac is
# the source of truth; the manifest is a generated projection consumed by
# shell/sync-plugins.sh on every surface. Run after installing/removing a plugin here.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_DIR/shell/plugins-manifest.txt"

python3 - "$OUT" <<'PY'
import json, sys
from pathlib import Path

out = Path(sys.argv[1])
home = Path.home()
settings = json.loads((home / ".claude/settings.json").read_text())
markets = json.loads((home / ".claude/plugins/known_marketplaces.json").read_text())

enabled = sorted(k for k, v in (settings.get("enabledPlugins") or {}).items() if v)
needed_markets = sorted({p.split("@", 1)[1] for p in enabled if "@" in p})

lines = [
    "# GENERATED by scripts/gen-plugins-manifest.sh - do not edit by hand.",
    "# Source of truth: the Mac's ~/.claude enabledPlugins (enabled only).",
    "# Consumed by shell/sync-plugins.sh on every surface.",
]
for name in needed_markets:
    src = markets.get(name, {}).get("source", {})
    if src.get("source") == "github":
        lines.append(f"marketplace {name} {src['repo']}")
    else:
        lines.append(f"# WARN marketplace {name}: non-github source, add manually")
lines += [f"plugin {p}" for p in enabled]
out.write_text("\n".join(lines) + "\n")
print(f"gen-plugins-manifest: wrote {out} ({len(enabled)} plugins, {len(needed_markets)} marketplaces)")
PY
